### ISSUE TITLE
Highlight structured map (:) style playbooks.

### ISSUE THREAD

**Issue by mxxcon** [clifford-github/sublime-ansible#15]
sublime-ansible does not seem to recognize structured list/map style playbooks as discussed in this article https://servercheck.in/blog/yaml-best-practices-ansible-playbooks-tasks

``` YAML
- name: Copy Phergie shell script into place.
  template:
    src: "templates/phergie.sh.j2"
    dest: "/home/{{ phergie_user }}/phergie.sh"
    owner: "{{ phergie_user }}"
    group: "{{ phergie_user }}"
    mode: 0755
```
