### ISSUE TITLE
FEATURE REQUEST: Nested vars with inline comments

### ISSUE THREAD

**Issue by miketwo** [clifford-github/sublime-ansible#19]
I tried to update the parser, and realized I have no idea how to write the crazy regexes needed for this. But here is an example:

```
################################################################################
# Nested vars definition with comments
- name: Install apt packages
  vars:
    - apt_packages:
      - libabc                 # a comment
      - lib123                 # another comment
###############################################################################
```

I think apt_packages should be formatted similarly to vars,
and inline comments should be grayed line normal comments.
