### ISSUE TITLE
Goto Symbol for tasks

### ISSUE THREAD

**Issue by brx75** [clifford-github/sublime-ansible#22]
Hi, 
I found very useful Sublime Text feature Goto Symbol (Ctrl + R).

I just did a very simple patch to have this working:

A new file Ansible.tmPreferences

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Symbol List: Tasks</string>
    <key>scope</key>
    <string>source.ansible keyword.other.ansible.task</string>
    <key>settings</key>
    <dict>
        <key>showInSymbolList</key>
        <integer>1</integer>
    </dict>
</dict>
</plist>
```

and a small change to tmLanguage:

```
- name: keyword.other.ansible.task
  match: \- (name\:|include\:) (.*)|(^(-)\w+\:)
  captures:
    '2': {name: string.quoted.double.ansible}

- name: keyword.other.ansible
  match: (^(\s*)\w+\:)
  captures:
    '2': {name: string.quoted.double.ansible}
```

`
