### ISSUE TITLE
FQCNs are not highlighted

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#27]
```yaml
- name: "install package"
  package:
    name: "package"

- name: "install package"
  ansible.builtin.package:
    name: "package"
```

<img width="226" alt="image" src="https://user-images.githubusercontent.com/3694534/119309837-27335780-bc6f-11eb-87bb-9521ad94648d.png">

tested in ST4, should be the same on ST3 though.
