### ISSUE TITLE
Coloring is confused by keywords in comments

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#31]
22.12.0

```yaml
---

- name: "install package"
  package:
    # Do not color this comment
    name: "package"
```

<img width="280" alt="image" src="https://user-images.githubusercontent.com/3694534/205470878-2feb5f41-be71-4d1c-832e-3df6e65bd701.png">
