### ISSUE TITLE
Coloring is confused by quotes in multiline strings

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#32]
22.12.0

```yaml
---

- name: register some variables
  set_fact:
    foo: bar
    baz: |
      foo
      bar
    qux: asdf

- name: register some variables
  set_fact:
    foo: bar
    baz: |
      foo'
      bar
    qux: asdf

- name: register some variables
  set_fact:
    foo: bar
    baz: |
      foo
      bar
    qux: asdf

- name: register some variables
  set_fact:
    foo: bar
    baz: |
      foo'
      bar
    qux: asdf
```

<img width="295" alt="image" src="https://user-images.githubusercontent.com/3694534/205471028-1fd3d9cf-ce4e-4a8c-90a5-cdbc063f9a44.png">
