### ISSUE TITLE
XML string values have strange highlighting

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#33]
22.12.0

```yaml
---

- community.general.xml:
    xmlstring: <?xml version='1.0' encoding='UTF-8'?><foo version="1"></foo>
    xpath: /foo
    add_children: "{{ myvar }}"
    pretty_print: true
  register: xml_str
```

<img width="621" alt="image" src="https://user-images.githubusercontent.com/3694534/205471201-9deab0cb-559b-4568-a496-bc2232a2c4bd.png">
