### ISSUE TITLE
Closing brackets in text are highlighted

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#34]
22.12.0

```yaml
---

- name: patch some xml
  community.general.xml:
    path: "{{ xml_path }}"
    xpath: /foo/bar[@name='baz']/qux
    state: absent
```

<img width="315" alt="image" src="https://user-images.githubusercontent.com/3694534/205471484-f5680875-84f6-49f2-8dcd-01069ac0109a.png">
