### ISSUE TITLE
Toggle comment does not work reliably

### ISSUE THREAD

**Issue by Nothing4You** [clifford-github/sublime-ansible#36]
f83b56aa0a236264daa291c24f586fdcb2bedee4

given
```yaml
---

- name: "install package"
  package:
    # Do not color this comment
    name: "package"
```

lines 1-2 can be toggled to be commented via `Toggle Comment` action, but this cannot be undone by trying to toggle again.
line 3 cannot be commented this way.
lines 4-6 can be toggled without an issue.

using YAML syntax they can be toggled just fine.
