### ISSUE TITLE
Comment at the end of string block causes scope issue

### ISSUE THREAD

**Issue by mrmeszaros** [clifford-github/sublime-ansible#39]
The following code breaks the syntax highlighting:

```yaml
- name: Run stuff
  shell: |
    echo Hello
    # echo World!
  changed_when: no
```
Here, the colon `:` after `changed_when` colors as a string (yellowish) instead of a punctuation (white):

![sublime-ansible-block-comment-bug](https://user-images.githubusercontent.com/15245298/207307342-fe877485-357b-4301-9582-a7f1a05cb3a2.png)

Checking the scope, this seems to be caused by the `string.unquoted.block.yaml` scope not ending because the `# echo World!` line is interpreted as a comment instead of part of the string.
Here is a YAML syntax coloring:

![sublime-ansible-block-string-yaml](https://user-images.githubusercontent.com/15245298/207308029-c777f5fe-3ae2-4dc9-9a1e-566a046a4992.png)
